project:
    title: Reefscape detector
ls:
    key: 013d3341828430eee9e60a196b6b401d0bd1a143
    url: http://localhost:8080
ontology:
    a teal ball: algae
    a white PVC tube: coral
raw_dataset:
    path: raw
dataset:
    path: python/complete

test:
    input_path: dataset
    output_path: runs/test
    number_of_images: 4
    show: True
    save: true
grounding_dino:
    model_path: models/grounding_dino.pth
    confidence_threshold: 0.3
    box_threshold: 0.25
cli:
    mode: pretrain_mode
    verbose: true
prueba: prueba
